### ISSUE TITLE
village bug

### ISSUE THREAD

**Issue by Sz-Yuan** [Living-Lemming/Villager-Pickup-Mod#2]
The bug occurs when a player clicks on another villager while holding a villager spawn egg with components. Instead of spawning a normal villager with the components, it spawns a baby villager.

**Comment by Living-Lemming** [comment]
This is an issue with Minecraft spawn eggs, not villager pickup, I could add a check to prevent spawning a villager on another villager, and i might work on that someday.

**Comment by sternschnaube** [comment]
I was not aware of this bug, good to know @Sz-Yuan 😊 
Thanks for fixing it.

**Comment by sternschnaube** [comment]
Could you please explain why you not planning to fix this issue? 
I find a fix for this really important @Living-Lemming.
